name: dailyplanner
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  flutter_platform_widgets: ^0.32.2
  cupertino_icons: ^0.1.2
  flutter_svg: ^0.17.3+1
  easy_localization: ^2.2.1
  rxdart: ^0.24.1


  shared_preferences: ^0.5.7

  provider: ^4.1.3

  firebase_core: ^0.4.4+3
  firebase_database: ^3.1.5
  firebase_analytics: ^5.0.2
  firebase_auth: ^0.14.0+5
  google_sign_in: ^4.5.0


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - assets/
    - langs/ru.json
    - langs/en.json


